calculate_scores:
  description: >
    Calculate the total score of all the players represented as keys of the dictionary {player_cards} and their values represent 
    the list of cards they have.
    Use the cards scoring metric where numbers 2 to 10 have their corresponding number as scores, face cards are scored 10 and A 
    is scored 11. 
    If the total score of any player if more than 21 then the score of this player becomes 0.
  expected_output: >
    Else return only a dictionary like {player_cards} where the values should be the total scores of the corresponding players. 
  agent: scores_calculator
