card_adder_for_user:
  description: > 
    Randomly generate 1 card from a deck of playing cards for the player {player} represented as a keys of the dictionary of 
    players {player_cards}. 
    The card should be represented by numbers as '2' or faces as 'K' and ace as 'A'. 
    Update the list of cards for the player {player} in the dictionary with the additional card. 
  expected_output: >
    Finally return the updated dictionary. The output should contain only the updated dictionary and no additional text. 
  agent: card_adder